/***************************************************
 * PEG Parser - Generated By YAPP Parser Generator *
 ***************************************************/

#ifndef CLIPPEREXPRESSIONPARSER_INCLUDE
#define CLIPPEREXPRESSIONPARSER_INCLUDE

#include "yapp_defs.h"
#include "yapp_node.h"
#include "yapp_buffer.h"
#include "yapp_rule.h"
#include "yapp_parser_error.h"
#include "yapp_trace_parser.h"
#include "yapp_mem_manager.h"

typedef struct {
   INT32 index;
   YAPP_BUFFER *buffer;
   YAPP_MEM_MANAGER *memoryManager;
   BOOL currentRuleIsAtomic;
   YAPP_NODE *currentNode;
   YAPP_NODE *lastNodeCreated;
   INT32 variable_ruleMemoStart;
   INT32 variable_ruleMemoEnd;
   YAPP_NODE *variable_ruleMemoFirstNode;
   INT32 parenthesesExpression_ruleMemoStart;
   INT32 parenthesesExpression_ruleMemoEnd;
   YAPP_NODE *parenthesesExpression_ruleMemoFirstNode;
   INT32 functionCall_ruleMemoStart;
   INT32 functionCall_ruleMemoEnd;
   YAPP_NODE *functionCall_ruleMemoFirstNode;
   INT32 ifInLine_ruleMemoStart;
   INT32 ifInLine_ruleMemoEnd;
   YAPP_NODE *ifInLine_ruleMemoFirstNode;
   INT32 aliasedField_ruleMemoStart;
   INT32 aliasedField_ruleMemoEnd;
   YAPP_NODE *aliasedField_ruleMemoFirstNode;
   INT32 parameter_ruleMemoStart;
   INT32 parameter_ruleMemoEnd;
   YAPP_NODE *parameter_ruleMemoFirstNode;
   INT32 logicalLiteral_ruleMemoStart;
   INT32 logicalLiteral_ruleMemoEnd;
   YAPP_NODE *logicalLiteral_ruleMemoFirstNode;
   INT32 nilValue_ruleMemoStart;
   INT32 nilValue_ruleMemoEnd;
   YAPP_NODE *nilValue_ruleMemoFirstNode;
   INT32 literal_ruleMemoStart;
   INT32 literal_ruleMemoEnd;
   YAPP_NODE *literal_ruleMemoFirstNode;
   INT32 dateTimeLiteral_ruleMemoStart;
   INT32 dateTimeLiteral_ruleMemoEnd;
   YAPP_NODE *dateTimeLiteral_ruleMemoFirstNode;
   INT32 integerNumber_ruleMemoStart;
   INT32 integerNumber_ruleMemoEnd;
   YAPP_NODE *integerNumber_ruleMemoFirstNode;
   INT32 timePattern_ruleMemoStart;
   INT32 timePattern_ruleMemoEnd;
   YAPP_NODE *timePattern_ruleMemoFirstNode;
   INT32 datePattern_ruleMemoStart;
   INT32 datePattern_ruleMemoEnd;
   YAPP_NODE *datePattern_ruleMemoFirstNode;
   INT32 expression_ruleMemoStart;
   INT32 expression_ruleMemoEnd;
   YAPP_NODE *expression_ruleMemoFirstNode;
   INT32 orExpression_ruleMemoStart;
   INT32 orExpression_ruleMemoEnd;
   YAPP_NODE *orExpression_ruleMemoFirstNode;
   INT32 optionalAndExpression_ruleMemoStart;
   INT32 optionalAndExpression_ruleMemoEnd;
   YAPP_NODE *optionalAndExpression_ruleMemoFirstNode;
   INT32 andExpression_ruleMemoStart;
   INT32 andExpression_ruleMemoEnd;
   YAPP_NODE *andExpression_ruleMemoFirstNode;
   INT32 optionalRelationalExpression_ruleMemoStart;
   INT32 optionalRelationalExpression_ruleMemoEnd;
   YAPP_NODE *optionalRelationalExpression_ruleMemoFirstNode;
   INT32 relationalExpression_ruleMemoStart;
   INT32 relationalExpression_ruleMemoEnd;
   YAPP_NODE *relationalExpression_ruleMemoFirstNode;
   INT32 optionalMathExpression_ruleMemoStart;
   INT32 optionalMathExpression_ruleMemoEnd;
   YAPP_NODE *optionalMathExpression_ruleMemoFirstNode;
   INT32 mathExpression_ruleMemoStart;
   INT32 mathExpression_ruleMemoEnd;
   YAPP_NODE *mathExpression_ruleMemoFirstNode;
   INT32 atomicExpression_ruleMemoStart;
   INT32 atomicExpression_ruleMemoEnd;
   YAPP_NODE *atomicExpression_ruleMemoFirstNode;
   INT32 prefixedExpression_ruleMemoStart;
   INT32 prefixedExpression_ruleMemoEnd;
   YAPP_NODE *prefixedExpression_ruleMemoFirstNode;
   INT32 stringLiteral_ruleMemoStart;
   INT32 stringLiteral_ruleMemoEnd;
   YAPP_NODE *stringLiteral_ruleMemoFirstNode;
   INT32 numberLiteral_ruleMemoStart;
   INT32 numberLiteral_ruleMemoEnd;
   YAPP_NODE *numberLiteral_ruleMemoFirstNode;
   INT32 anyIdentifier_ruleMemoStart;
   INT32 anyIdentifier_ruleMemoEnd;
   YAPP_NODE *anyIdentifier_ruleMemoFirstNode;
   INT32 identifier_ruleMemoStart;
   INT32 identifier_ruleMemoEnd;
   YAPP_NODE *identifier_ruleMemoFirstNode;
   INT32 identifierPattern_ruleMemoStart;
   INT32 identifierPattern_ruleMemoEnd;
   YAPP_NODE *identifierPattern_ruleMemoFirstNode;
   INT32 whitespace_ruleMemoStart;
   INT32 whitespace_ruleMemoEnd;
   YAPP_NODE *whitespace_ruleMemoFirstNode;
   INT32 lineComment_ruleMemoStart;
   INT32 lineComment_ruleMemoEnd;
   YAPP_NODE *lineComment_ruleMemoFirstNode;
   INT32 blockComment_ruleMemoStart;
   INT32 blockComment_ruleMemoEnd;
   YAPP_NODE *blockComment_ruleMemoFirstNode;
   INT32 spacing_ruleMemoStart;
   INT32 spacing_ruleMemoEnd;
   YAPP_NODE *spacing_ruleMemoFirstNode;
   INT32 continueNL_ruleMemoStart;
   INT32 continueNL_ruleMemoEnd;
   YAPP_NODE *continueNL_ruleMemoFirstNode;
   INT32 optionalSpacing_ruleMemoStart;
   INT32 optionalSpacing_ruleMemoEnd;
   YAPP_NODE *optionalSpacing_ruleMemoFirstNode;
} ClipperExpressionParser;

extern YAPP_RULE TERMINAL_RULE;

extern YAPP_RULE CLIPPEREXPRESSION_CLIPPER_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_VARIABLE;

extern YAPP_RULE CLIPPEREXPRESSION_ASSIGNMENT_OPERATOR;

extern YAPP_RULE CLIPPEREXPRESSION_EXPRESSION_LIST;

extern YAPP_RULE CLIPPEREXPRESSION_PARENTHESES_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_PAR_PARAMETERS;

extern YAPP_RULE CLIPPEREXPRESSION_FUNCTION_CALL;

extern YAPP_RULE CLIPPEREXPRESSION_IF_IN_LINE;

extern YAPP_RULE CLIPPEREXPRESSION_ALIASED_FIELD;

extern YAPP_RULE CLIPPEREXPRESSION_PARAMETER;

extern YAPP_RULE CLIPPEREXPRESSION_COMMA_PARAMETER;

extern YAPP_RULE CLIPPEREXPRESSION_PARAMETER_COMMA_LIST;

extern YAPP_RULE CLIPPEREXPRESSION_PARAMETERS_LIST;

extern YAPP_RULE CLIPPEREXPRESSION_OPTIONAL_PARAMETERS_LIST;

extern YAPP_RULE CLIPPEREXPRESSION_LOGICAL_LITERAL;

extern YAPP_RULE CLIPPEREXPRESSION_NIL_VALUE;

extern YAPP_RULE CLIPPEREXPRESSION_LITERAL;

extern YAPP_RULE CLIPPEREXPRESSION_DATE_TIME_LITERAL;

extern YAPP_RULE CLIPPEREXPRESSION_TIME_LITERAL;

extern YAPP_RULE CLIPPEREXPRESSION_INTEGER_NUMBER;

extern YAPP_RULE CLIPPEREXPRESSION_DATE_PATTERN;

extern YAPP_RULE CLIPPEREXPRESSION_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_OR_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_OPTIONAL_AND_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_AND_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_RELATIONAL_OPERATOR;

extern YAPP_RULE CLIPPEREXPRESSION_OPTIONAL_RELATIONAL_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_RELATIONAL_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_MATH_OPERATOR;

extern YAPP_RULE CLIPPEREXPRESSION_OPTIONAL_MATH_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_MATH_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_ATOMIC_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_PREFIXED_EXPRESSION;

extern YAPP_RULE CLIPPEREXPRESSION_PREFIX_OPERATOR;

extern YAPP_RULE CLIPPEREXPRESSION_STRING_LITERAL;

extern YAPP_RULE CLIPPEREXPRESSION_NUMBER_LITERAL;

extern YAPP_RULE CLIPPEREXPRESSION_ANY_IDENTIFIER;

extern YAPP_RULE CLIPPEREXPRESSION_IDENTIFIER;

extern YAPP_RULE CLIPPEREXPRESSION_WHITESPACE;

extern YAPP_RULE CLIPPEREXPRESSION_LINE_COMMENT;

extern YAPP_RULE CLIPPEREXPRESSION_BLOCK_COMMENT;

extern YAPP_RULE CLIPPEREXPRESSION_END_STMT;

extern YAPP_RULE CLIPPEREXPRESSION_SPACING;

extern YAPP_RULE CLIPPEREXPRESSION_CONTINUE_NL;

extern YAPP_NODE* clipperExpressionParser_parse(ClipperExpressionParser *parser);
extern ClipperExpressionParser* clipperExpressionParser_new(YAPP_BUFFER *inputBuffer);
extern ClipperExpressionParser* clipperExpressionParser_newManaged(YAPP_MEM_MANAGER *memoryManager, YAPP_BUFFER *inputBuffer);
extern void clipperExpressionParser_free(ClipperExpressionParser *parser);
extern void clipperExpressionParser_setTraceParser(ClipperExpressionParser *parser, YAPP_TRACE_PARSER *tracePath);
extern void clipperExpressionParser_setTrace(ClipperExpressionParser *parser, BOOL trace);
extern YAPP_PARSER_ERROR* clipperExpressionParser_getMismatches(ClipperExpressionParser *parser);
extern INT32 clipperExpressionParser_rulesCount(ClipperExpressionParser *parser);
#endif
